### PR TITLE
Add a test to make sure XML is escaped properly

### PR DESCRIPTION
**Pull request by aredridel**
Presently fails due to inadequate output escaping.

### CODE REVIEW

**Comment by bcoe** [comment]
@aredridel ping, do you know if a `CDATA` block would do the trick for a plist file, I'm going to work on getting a release of ndm out this week.

**Comment by aredridel** [comment]
Yep! Should work fine, at least on OSX 10.10.

**Comment by aredridel** [comment]
(unsure about previous, suspect it'd work)

**Comment by bcoe** [comment]
@aredridel I've addressed this issue in:

https://github.com/npm/ndm/pull/109

released in `yargs@3.9.0`.

**Pull request closed without merging**
